title: Théo Lenavetier
description: Postdoctoral researcher in Soft Matter Hydrodynamics
theme: minima

header_pages:
  - index.md
  - cv.md
  - research.md
  - publications.md
  - gallery.md
  - contact.md
